name: mussel-finder
dependencies:
  # - Python=3.11.7
  - opencv=4.9.0
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - scikit-image
  - matplotlib
  - openpyxl
  - ipykernel
  - pip
  - pip:
    - transformers==4.36.2
    - accelerate 
    - datasets 
    - evaluate